(()=>{'use strict';
const VERSION='v11.2.2';
const KEY='hesab-man-local-lock-v11.2.2';
const fa=v=>String(v||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/\D/g,'').slice(0,6);
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('hesab-man:'+v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function version(){document.querySelectorAll('.version').forEach(e=>e.textContent=VERSION)}
const css=document.createElement('style');css.textContent=`#hmLock{position:fixed;inset:0;z-index:2147483647;background:#073f42;display:flex;align-items:center;justify-content:center;padding:24px;direction:rtl;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Tahoma,sans-serif}#hmLock *{box-sizing:border-box}.hmCard{width:min(430px,94vw);background:#fff;border-radius:28px;padding:28px 24px;text-align:center;box-shadow:0 20px 60px #0003;color:#0f172a}.hmLogo{font-size:42px;margin-bottom:8px}.hmCard h2{margin:4px 0 6px;font-size:25px}.hmSub{color:#64748b;font-size:14px;margin-bottom:20px}.hmInput{width:100%;height:58px;border:1px solid #cbd5e1;border-radius:16px;text-align:center;font-size:22px;letter-spacing:8px;margin:7px 0;outline:none}.hmInput:focus{border-color:#0f766e;box-shadow:0 0 0 3px #0f766e18}.hmBtn{width:100%;height:56px;border:0;border-radius:16px;background:#11877d;color:white;font-size:17px;font-weight:800;margin-top:9px}.hmMsg{min-height:24px;color:#b91c1c;font-size:13px;margin-top:10px}.hmNote{color:#94a3b8;font-size:12px;line-height:1.8;margin-top:15px}#hmLockNow{position:fixed;left:12px;top:72px;z-index:80;width:40px;height:40px;border-radius:13px;border:1px solid #dbe5ef;background:#fff;box-shadow:0 6px 20px #0002;font-size:18px}`;document.head.appendChild(css);
let overlay=null;
function remove(){overlay?.remove();overlay=null;button();version()}
function input(ph){const i=document.createElement('input');i.className='hmInput';i.type='password';i.inputMode='numeric';i.autocomplete='off';i.maxLength=6;i.placeholder=ph;i.oninput=()=>i.value=fa(i.value);return i}
function base(title,sub){const c=document.createElement('div');c.className='hmCard';c.innerHTML=`<div class="hmLogo">🔐</div><h2>${title}</h2><div class="hmSub">${sub}</div>`;return c}
function mount(c){if(!overlay){overlay=document.createElement('div');overlay.id='hmLock';document.body.appendChild(overlay)}overlay.replaceChildren(c)}
function setup(){const c=base('ساخت رمز برنامه','یک رمز ۴ تا ۶ رقمی فقط برای همین دستگاه تعیین کن');const a=input('رمز جدید');const b=input('تکرار رمز');const m=document.createElement('div');m.className='hmMsg';const btn=document.createElement('button');btn.className='hmBtn';btn.textContent='ذخیره رمز';btn.onclick=async()=>{m.textContent='';if(a.value.length<4)return m.textContent='رمز باید حداقل ۴ رقم باشد.';if(a.value!==b.value)return m.textContent='تکرار رمز یکسان نیست.';btn.disabled=true;save({hash:await hash(a.value)});remove()};c.append(a,b,btn,m);const n=document.createElement('div');n.className='hmNote';n.textContent='این قفل کاملاً محلی است و هیچ تغییری در Supabase یا اطلاعات مالی ایجاد نمی‌کند.';c.appendChild(n);mount(c)}
function lock(){const s=load();if(!s.hash)return setup();const c=base('حساب من','ورود امن به اطلاعات مالی');const a=input('رمز برنامه');const m=document.createElement('div');m.className='hmMsg';const btn=document.createElement('button');btn.className='hmBtn';btn.textContent='ورود';let busy=false;btn.onclick=async()=>{if(busy)return;busy=true;m.textContent='';const ok=(await hash(a.value))===s.hash;if(ok)remove();else{m.textContent='رمز صحیح نیست.';a.value=''}busy=false};a.onkeydown=e=>{if(e.key==='Enter')btn.click()};c.append(a,btn,m);const n=document.createElement('div');n.className='hmNote';n.textContent='این رمز فقط قفل برنامه روی همین دستگاه است و به رمز Supabase ارتباطی ندارد.';c.appendChild(n);mount(c)}
function button(){if(document.getElementById('hmLockNow'))return;const b=document.createElement('button');b.id='hmLockNow';b.type='button';b.textContent='🔒';b.title='قفل کردن الآن';b.onclick=lock;document.body.appendChild(b)}
window.addEventListener('DOMContentLoaded',()=>{version();setTimeout(lock,120)},{once:true});
})();
